version: '3'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - nats

  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: 
      - "-js"
      - "-m=8222"
    volumes:
      - nats_data:/data

  db:
    image: 'postgres:16.2'
    hostname: postdb
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PW}'
      POSTGRES_DB: '${PG_DB}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    environment:
      DATABASE_URL: 'postgresql://${PG_USER}:${PG_PW}@db:5432/${PG_DB}?schema=public'
    depends_on:
      - db
    command: npx prisma migrate deploy

volumes:
  nats_data:
    driver: local
  postgres_data:
    driver: local